# Generated by Django 4.1.7 on 2023-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persoonsLijst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aNummer', models.CharField(max_length=100)),
                ('bsn', models.CharField(max_length=100)),
                ('naam', models.CharField(max_length=100)),
                ('telefoon', models.CharField(max_length=100)),
                ('geboorteDatum', models.CharField(max_length=100)),
                ('geboortePlaats', models.CharField(max_length=100)),
                ('geboorteLand', models.CharField(max_length=100)),
                ('geslachtsaanduiding', models.CharField(max_length=100)),
                ('nationaliteit1', models.CharField(max_length=100)),
                ('nationaliteit2', models.CharField(max_length=100)),
                ('huidigePostcode', models.CharField(max_length=100)),
                ('huidigeHuisnummer', models.CharField(max_length=100)),
                ('huidigeWoonplaats', models.CharField(max_length=100)),
                ('huidigeAdresGeldig', models.CharField(max_length=100)),
                ('vorigePostcode', models.CharField(max_length=100)),
                ('vorigeHuisnummer', models.CharField(max_length=100)),
                ('vorigeWoonplaats', models.CharField(max_length=100)),
                ('vorigeAdresGeldig', models.CharField(max_length=100)),
                ('volgnummer', models.CharField(max_length=100)),
            ],
        ),
    ]
