# Generated by Django 4.1.7 on 2023-04-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepoc', '0003_alter_messages_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='messagesSummary',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('messageId', models.CharField(max_length=100)),
                ('generationDate', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=100)),
                ('callMethod', models.CharField(max_length=100)),
                ('messageSize', models.CharField(max_length=100)),
                ('senderId', models.CharField(max_length=100)),
                ('recipientId', models.CharField(max_length=100)),
                ('callResponseTimeMs', models.CharField(max_length=100)),
                ('callResponse', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='recipientId',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
    ]
