# Generated by Django 4.1.7 on 2023-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepoc', '0004_messagessummary_messages_recipientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='messageId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='messages',
            name='recipientId',
            field=models.CharField(max_length=50),
        ),
    ]
