# Generated by Django 4.1.7 on 2023-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepoc', '0005_alter_messages_messageid_alter_messages_recipientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagessummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
