# Generated by Django 4.1.7 on 2023-04-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepoc', '0006_alter_messagessummary_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagessummary',
            old_name='callMethod',
            new_name='callMethods',
        ),
    ]
