# Generated by Django 4.1.7 on 2023-04-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepoc', '0007_rename_callmethod_messagessummary_callmethods'),
    ]

    operations = [
        migrations.CreateModel(
            name='messagesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageId', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='persoonsLijst',
        ),
    ]
