# Generated by Django 4.1.7 on 2023-04-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepoc', '0008_messageslist_delete_persoonslijst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='messageId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='recipientId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
