# Generated by Django 4.1.7 on 2023-04-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepoc', '0009_alter_messages_message_alter_messages_messageid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
